### ISSUE TITLE
Crashes randomly when set to "Window Title" and working with Skyrim

### ISSUE THREAD

**Issue by tony8128** [PsychedelicShayna/cursor-locker#10] opened 2021-09-15 15:25 UTC
I am playing the original Skyrim release (the November 2011 one) and the application will crash at random times. I've had it crash when I was just launching Skyrim, and I've had it crash after an hour or two of usage.

It doesn't affect the function of the application. Just a bit annoying to have to re-open it once in a while.

I'm not sure if the application keeps a log anywhere, but I've not been able to find it.

**Comment by MisanthropicShayna** [comment] 2021-11-14 20:51
@tony8128 Currently the program doesn't store logs anywhere, so without any additional information it's quite hard to track down the source of these crashes. I'll work on implementing a logging system to better help track down these sorts of issues, but in the meantime, could you confirm that this only happens when using the window title activation mode, and no other activation mode? 

Also, I've recently released a couple of updates since you opened this issue, if you could confirm that this is still an ongoing issue on the latest version, that would be great. 

I apologize for my absence.

**Comment by tony8128** [comment] 2021-11-17 04:06
Thank you for the reply. Unfortunately I seem to have modded my Skyrim too heavily and it started crashing too frequently to properly play. If I ever figure out how to stabilize the game, then I'd be more than happy to help you test the latest version out further.

**Comment by tony8128** [comment] 2021-11-19 01:56
I've tried to tweak my mods a bit and managed to stabilized my skyrim enough to be playable. And I can confirm the app still crashes, although I was unable to tell when it crashed as I only noticed it after going through a lengthy dungeon and alt+tab out.

**Comment by MisanthropicShayna** [comment] 2021-11-19 04:26
Thank you for confirming! I'm currently in the processing of developing v4.0 of the application, as seen on the `development-v4.0.0` branch, which is almost a total remake of the entire codebase, built upon a much stabler and well designed foundation. The current version abuses multi-threading, accomplishes some of its functionality in a less than ideal manner, and quite frankly isn't built on a very stable foundation. These random crashes don't surprise me. It shouldn't be much longer until v4.0 is out, but until then, any sort of further bug hunting on the old codebase won't really be of much use as almost nothing from the old codebase still applies to the new codebase. I'm going to leave this issue open for when v4.0 is released to see if the issue still persists. It's going to run a whole heck of a lot smoother, that much I can guarantee.

**Comment by tony8128** [comment] 2021-11-20 01:16
No problem, and thank you for your continued update! Looking forward to your 4.0 release!

**Comment by PsychedelicShayna** [comment] 2021-12-29 06:47
@tony8128 Hey, just letting you know that v4.0.0 is out now, if you'd still like to test it for bugs, and the crash you experienced. I might have missed a couple of things, let me know if you encounter any issues! I've migrated to Qt6, which I hope doesn't cause too many compatibility issues.

**Comment by PsychedelicShayna** [comment] 2022-03-15 14:14
@tony8128 I'm closing the issue, as there hasn't been any further reply after 4 months. I haven't been able to reproduce this problem, and it appears somewhat rare, although people have reportedly solved it by running the program with administrator permissions, suggesting that it might be an issue with attempting to read the Window title of an elevated process on some systems, although I haven't run into this issue myself.

**Closed as completed by PsychedelicShayna** 2022-03-15 14:14 UTC
Labels: bug
